### ISSUE TITLE
Squash new repos' history

### ISSUE THREAD

**Issue by contolini** [cfpb/kratos#24]
Kratos creates a new GH repo by [pulling down the OSPT repo](https://github.com/cfpb/kratos/blob/master/src/workers/gh_client.coffee#L128). This works great _but_ it causes new projects to start with OSPT's entire git history which isn't good.

The simplest way to reset new repos' history seems to be: `git reset $(git commit-tree HEAD^{tree} -m "Initial commit")` as [seen here](http://stackoverflow.com/questions/1657017/squash-all-git-commits-into-a-single-commit/23486788#23486788). Will this command work on prod? Or will it fail when it tries to commit because a git user hasn't been configured on the server?

**Comment by Scotchester** [comment]
See also cfpb/devdash#48

I don't think you have to take that extra step. You can do what's called a "shallow clone". More info here: http://www.perforce.com/blog/141218/git-beyond-basics-using-shallow-clones

**Comment by contolini** [comment]
:+1: You beat me to it.

Shallow clone is a great idea. Although, it leaves the latest commit in the repo's history so something like `git commit --amend -m "Initial commit"` after the clone would be ideal.

**Comment by contolini** [comment]
Closing this in favor of the other issue.
